### ISSUE TITLE
formation flight

### ISSUE THREAD

**Issue by 2black0** [alduxvm/DronePilot#4]
for formation flight (maybe 3 drones or more) we need to identify the number of drone before send MSP data,

btw, any idea how send MSP data to right drone?

**Comment by alduxvm** [comment]
The first step is to know your intentions and structure, what type of swarm are you attempting to do? does each vehicle has a companion computer on board? you want a master computer to send commands to each CC? if thats the case, then just send commands via UDP to different addresses no need to do any kind of identification

If identification is required, my pymultiwii library should be modified to ask the board for its version and then include some sort of identifier based on the version, trying to follow the MSP_IDENT command (http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol).

As this is not an issue with this repository but more like a consultation to me, I will close the issue and ask you to send me an email so I can handle better your questions. Thanks!
